--Estructura de la Base de Datos
--Tabla ESTADISTICAS
CREATE TABLE ESTADISTICAS_R (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    SERIE_NUMEROS VARCHAR2(4000),
    MEDIA NUMBER(10,2),
    MEDIANA NUMBER(10,2),
    MODA NUMBER(10,2),
    CONSTRAINT PK_ESTADISTICAS_R PRIMARY KEY(ID)
);

COMMIT;

--consulta de Datos
SELECT * FROM ESTADISTICAS_R;
